name: Test Brevitas-XIR integration

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.6', '3.7']
        pytorch_version: ['1.4.0']
        platform: ['ubuntu-latest']



    defaults:
      run:
        shell: bash -l {0}
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2

    - name: Cache Vitis AI conda channel
      uses: actions/cache@v2
      id: conda-cache
      with:
          path: conda-channel
          key: 1.3.598-01

    - name: Download Vitis AI conda channel
      run: wget -O $GITHUB_WORKSPACE/conda-channel.tar.gz https://www.xilinx.com/bin/public/openDownload?filename=conda-channel_1.3.598-01.tar.gz

    - name: Unpack Vitis AI conda channel
      run: tar -xzvf $GITHUB_WORKSPACE/conda-channel.tar.gz -C $GITHUB_WORKSPACE/

    - name: Set conda channel path
      run: echo "CONDA_CHANNEL_PATH=$GITHUB_WORKSPACE/conda-channel" >> $GITHUB_ENV

    - name: Install Nox dependencies
      run: pip install -r requirements/requirements-nox.txt

    - name: Run Nox session for Brevitas-XIR integration
      shell: bash
      run: nox -v -s tests_brevitas_xir_integration-${{ matrix.python_version }}\(\pytorch_${{ matrix.pytorch_version }}\)


